backend:
  name: github
  branch: master
  repo: RLBurst/portfolio

media_folder: content/assets

collections:
  - name: blog
    label: 'Post'
    folder: 'content/blog'
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'date', label: Date, widget: 'datetime' }
      - { name: 'body', label: 'Body', widget: 'markdown' }
